### ISSUE TITLE
focus / blur events not fired when using getStateForAction

### ISSUE THREAD

**Issue by pensierinmusica** [react-navigation/react-navigation-redux-helpers#26]
Hi,

I'm using React Navigation integrated with Redux. I've noticed that the focus / blur events are not fired when I change route using `getStateForAction`.

For example let's imagine a reducer that returns this:

```js
const newState = AppNavigator.router.getStateForAction(NavigationActions.back(args), state);
```

Is such usage expected to not fire a focus event for the route it lands in, or is it due to a bug?

Thanks!

**Comment by Ashoat** [comment]
Some discussion in this issue: #25

Please correct me if I'm wrong, but I don't believe this is possible in React Navigation without Redux integration. It's not the intention of this library to provide functionality outside the scope of React Navigation, but it should be pretty easy to implement a custom `createReduxBoundAddListener` that doesn't filter any events out. I'm not sure if it'll work as you expect, though, since listening for focus/blur actions does not appear to be supported in React Navigation.

Going to close this now, but please let me know if I'm missing something.

**Comment by Ashoat** [comment]
`react-navigation-redux-helpers@1.1.1` introduces a new export called `createDidUpdateCallback` that should fix this issue. Refer to the [docs](https://github.com/react-navigation/react-navigation-redux-helpers) for how it's used.
